// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daxzuqftydurqjlibylr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRheHp1cWZ0eWR1cnFqbGlieWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzNTQ0NDEsImV4cCI6MjA5MDkzMDQ0MX0.ecaaV6iYup_3SRqrWl6YtjZIb89BfPqqczF0x72JILc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});